In [2]:
import pandas as pd

In [21]:
# importing required modules 
from zipfile import ZipFile 
  
# specifying the zip file name 
file_name = "/Users/DERJAN/Desktop/DLR-Projekt-Wetterdaten/klarchiv_05792_daily_his.zip"
  
# opening the zip file in READ mode 
with ZipFile(file_name, 'r') as zip: 
    # printing all the contents of the zip file 
    zip.printdir() 
  
    # extracting all the files 
    print('Extracting all the files now...') 
    zip.extractall('/Users/DERJAN/Desktop/DLR-Projekt-Wetterdaten/Unzipped_Data/') 
    print('Done!')

File Name                                             Modified             Size
Metadaten_Geographie_05792.txt                 2019-03-14 10:24:48          209
Metadaten_Geraete_Luftdruck_Stationshoehe_05792.html 2019-03-14 10:24:38         4294
Metadaten_Geraete_Luftdruck_Stationshoehe_05792.txt 2019-03-14 10:22:32          891
Metadaten_Geraete_Lufttemperatur_05792.html    2019-03-14 10:24:38         2746
Metadaten_Geraete_Lufttemperatur_05792.txt     2019-03-14 10:22:30          531
Metadaten_Geraete_Lufttemperatur_Maximum_05792.html 2019-03-14 10:24:38         2211
Metadaten_Geraete_Lufttemperatur_Maximum_05792.txt 2019-03-14 10:22:30          414
Metadaten_Geraete_Lufttemperatur_Minimum_05792.html 2019-03-14 10:24:38         2215
Metadaten_Geraete_Lufttemperatur_Minimum_05792.txt 2019-03-14 10:22:32          414
Metadaten_Geraete_Niederschlagshoehe_05792.html 2019-03-14 10:24:38         3263
Metadaten_Geraete_Niederschlagshoehe_05792.txt 2019-03-14 10:22:32          616
Metadaten_Geraete_Niederschlagshoehe_Ind_05792.html 2019-03-14 10:24:38         2749
Metadaten_Geraete_Niederschlagshoehe_Ind_05792.txt 2019-03-14 10:22:32          534
Metadaten_Geraete_Rel_Feuchte_05792.html       2019-03-14 10:24:38         3241
Metadaten_Geraete_Rel_Feuchte_05792.txt        2019-03-14 10:22:32          619
Metadaten_Geraete_Schneehoehe_05792.html       2019-03-14 10:24:38         2690
Metadaten_Geraete_Schneehoehe_05792.txt        2019-03-14 10:22:32          498
Metadaten_Geraete_Sonnenscheindauer_05792.html 2019-03-14 10:24:38         4930
Metadaten_Geraete_Sonnenscheindauer_05792.txt  2019-03-14 10:22:32         1024
Metadaten_Geraete_Windgeschwindigkeit_05792.html 2019-03-14 10:24:38         3258
Metadaten_Geraete_Windgeschwindigkeit_05792.txt 2019-03-14 10:22:32          618
Metadaten_Geraete_Windspitze_Maximum_05792.html 2019-03-14 10:24:38         3171
Metadaten_Geraete_Windspitze_Maximum_05792.txt 2019-03-14 10:22:32          618
Metadaten_Parameter_klima_tag_05792.html       2019-03-14 10:24:48        28242
Metadaten_Parameter_klima_tag_05792.txt        2019-03-14 10:24:44        10907
Metadaten_Stationsname_05792.html              2019-03-14 10:24:42          677
Metadaten_Stationsname_05792.txt               2019-03-14 10:24:42          103
produkt_klima_tag_19000801_20181231_05792.txt  2019-03-14 10:21:42      5899965
Extracting all the files now...
Done!

In [13]:
#produkt_klima_tag

data = pd.read_csv('/Users/DERJAN/Desktop/DLR-Projekt-Wetterdaten/klarchiv_05792_daily_his/produkt_klima_tag_19000801_20181231_05792.txt', sep=';')

data.head()

,STATIONS_ID,MESS_DATUM,QN_3,FX,FM,QN_4,RSK,RSKF,SDK,SHK_TAG,NM,VPM,PM,TMK,UPM,TXK,TNK,TGK,eor
0,5792,19000801,-999,-999.0,-999.0,5,-999.0,-999,15.0,5,0.0,3.9,715.3,3.6,50.0,6.2,-3.6,-999,eor
1,5792,19000802,-999,-999.0,-999.0,5,-999.0,-999,6.2,-999,5.0,8.3,713.7,5.2,88.0,12.6,2.2,-999,eor
2,5792,19000803,-999,-999.0,-999.0,5,-999.0,-999,1.3,-999,8.0,7.9,710.6,3.7,96.0,7.9,1.2,-999,eor
3,5792,19000804,-999,-999.0,-999.0,5,-999.0,-999,0.0,-999,8.0,6.3,706.3,-0.3,98.0,5.2,-2.8,-999,eor
4,5792,19000805,-999,-999.0,-999.0,5,-999.0,-999,0.0,10,8.0,4.4,705.9,-4.0,95.0,-0.9,-5.4,-999,eor

In [11]:
#

data = pd.read_csv('/Users/DERJAN/Desktop/DLR-Projekt-Wetterdaten/klarchiv_05792_daily_his/Metadaten_Geographie_05792.txt', sep=';')

data.tail()

,Stations_id,Stationshoehe,Geogr.Breite,Geogr.Laenge,von_datum,bis_datum,Stationsname
0,5792,2964.0,47.4214,10.9854,19000719,20071016,Zugspitze
1,5792,2964.0,47.4209,10.9847,20071017,,Zugspitze

In [14]:
data = pd.read_csv('/Users/DERJAN/Desktop/DLR-Projekt-Wetterdaten/klarchiv_05792_daily_his/Metadaten_Geraete_Luftdruck_Stationshoehe_05792.txt', sep=';')

data.head()

,Stations_ID,Stationsname,Geo. Laenge [Grad],Geo. Breite [Grad],Stationshoehe [m],Barometerhoehe ueber NN [m],Von_Datum,Bis_Datum,Geraetetyp Name,Messverfahren,eor,Unnamed: 11
0,5792,Zugspitze,10.99,47.42,2964.0,2962.6,19000801.0,19800831.0,Stationsbarometer,"Luftdruckmessung, konv.",eor,NaN
1,5792,Zugspitze,10.99,47.42,2964.0,2962.6,19860313.0,20071016.0,Digitalbarometer AIR-DB,"Luftdruckmessung, elektr.",eor,NaN
2,5792,Zugspitze,10.98,47.42,2964.0,2960.2,20071017.0,20090805.0,Digitalbarometer AIR-DB,"Luftdruckmessung, elektr.",eor,NaN
3,5792,Zugspitze,10.98,47.42,2964.0,2960.2,20090806.0,20121114.0,Digitalbarometer PTB 330,"Luftdruckmessung, elektr.",eor,NaN
4,5792,Zugspitze,10.98,47.42,2964.0,2960.2,20121115.0,20141015.0,Luftdrucksensor Vaisala PTB 220,"Luftdruckmessung, elektr.",eor,NaN